### ISSUE TITLE
[Feature] todo 기능 추가

### ISSUE THREAD

**Issue by JH713** [goorung/Gitodo#42]
### 💡 개요

- todo view에 기능을 추가합니다

### 💻 기능 명세

 - [x] todoview의 tintColor 고치기 
 - [x] 투두 여러 줄 가능하게 만들기
 - [x] 투두 비었을 때 라벨 추가
